name: 'comment-hider'
description: 'Github Action to hide Bot comments'
branding:
  color: gray-dark
  icon: check
author: 'alechartung'
inputs:
  github_token:
    description: 'The GitHub token used to create an authenticated client'
    required: true
  comment_text:
    description: 'Comment text to delete'
    required: true
  hide_reason:
    description: 'Reasons to hide comments'
    default: 'OUTDATED'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
